name: ADF Dev to Staging

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: dev_adf_publish

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
          azcliversion: 2.52.0
          inlineScript: |
            az -v

    # - name: Az CLI login
    #   uses: azure/login@v1
    #   with:
    #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
    #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #    # client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    # - name: Login to Azure
    #   run: |
    #     whoami
    #     sudo az login --service-principal -u 'b6250f57-c5e4-4b45-ad54-225085634ba8' -p 'wxx8Q~kOwFV81x6w8k1.qjs3VI9AfkyfF63yvbTt' --tenant '4a161032-d6d8-4570-837b-ebb55dd3e1c3'

    # - name: Deploy ADF to Staging
    #   run: |
    #     # Replace 'your-adf-folder' with the path to your ADF ARM templates
    #     sudo az deployment group create --resource-group YourResourceGroup --template-file program42adf/ARMTemplateForFactory.json --parameters program42adf/ARMTemplateParametersForFactory.json
    - name: become root
      run: sudo -i

    - name: Login via Az module
      uses: azure/login@v1
      with:
        client-id: b6250f57-c5e4-4b45-ad54-225085634ba8
        tenant-id: 4a161032-d6d8-4570-837b-ebb55dd3e1c3
        subscription-id: 57c22230-c355-4293-8493-61057d85f0cc
        enable-AzPSSession: true

    - name: data-factory-deploy
      uses: Azure/data-factory-deploy-action@v1.2.0
      with:
        resourceGroupName: myrg
        dataFactoryName: prohram43adf
        armTemplateFile: program42adf/ARMTemplateForFactory.json
        armTemplateParametersFile: program42adf/ARMTemplateParametersForFactory.json
        additionalParameters: '"Copy Data1"="stg copy"'
