name: ADF Dev to Staging

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: dev_adf_publish

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
          azcliversion: 2.52.0
          inlineScript: |
            az -v

    - name: Az CLI login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
       # client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    # - name: Login to Azure
    #   run: az login --service-principal -u ${{ secrets.AZURE_SERVICE_PRINCIPAL_CLIENT_ID }} -p ${{ secrets.AZURE_SERVICE_PRINCIPAL_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_SERVICE_PRINCIPAL_TENANT_ID }}

    - name: Deploy ADF to Staging
      run: |
        # Replace 'your-adf-folder' with the path to your ADF ARM templates
        az deployment group create --resource-group YourResourceGroup --template-file program42adf/ARMTemplateForFactory.json --parameters program42adf/ARMTemplateParametersForFactory.json
